/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.isu.cs.cs2263;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {



    @Override
    public void start(Stage primaryStage) throws IOException {
        Parent parent = FXMLLoader.load(getClass().getResource("/fxml/HumanInterface.fxml"));

        Scene scenery = new Scene(parent);

        primaryStage.setScene(scenery);
        primaryStage.show();



    }

}
